### ISSUE TITLE
Oauth flow

### ISSUE THREAD

**Issue by NutanNiraula** [mikepham1011/nimble-survey-app-ios#4]
Hi, it is nice to meet you through this code review. There are couple of interesting choices you have made in your code submission. We would love to know more about your decisions and create issues where we think there could be more improvements. Please address these using proper gitflow (creating new branch, creating PR and merging the code) or feel free to give your opinion about the implementation. 

It was really interesting to see you implement crypo to obfuscate the username and password but you used device date and time to calculate the timeout for the token, do you think it would be better to implement oauth flow here to refresh token when the request to the surveys api fail? Maybe having an interceptor layer in the network layer to adapt and retry the requests would be more scalable for the app so that there can be implementations like force-upgrade, force-logout and header adaption in each requests? This would make the network layer also extensible for ssl pinning down the road. Would you consider implementing an interceptor layer?

**Comment by mikepham1011** [comment]
Hi @NutanNiraula, it was a great pleasure to hear from you. I am happy to provide feedbacks on the choices I have made so far, please feel free to ask me more if you have additional questions after seeing my responses.

For the Oauth flow question, I think you are absolutely right that we need an interceptor layer for future scalability and enhancement, since in my current projects I am also implementing that mechanism for my API and network handlers. My reason for choosing this approach is that as of now, this project is just a small size project, and my goal is to simplify certain parts of the application that I can deliver a functional app in a timely manner. This way, it will help me deliver a product with a proper balance between work quality and work deliverables punctuality. 
In general, I think the interceptor layer is definitely a must for standard medium-to-big projects. 
Thank you for your suggestion! I will definitely implement this mechanism.

**Comment by NutanNiraula** [comment]
It's a good response! Your approach is indeed practical. Still I would love to see what you would come up with for the network layer. Sometimes a little work upfront to create proper level of abstraction depending on project size can save alot of time later and help teams move fast and also helps to scale well when there is need. There definitely should be a balance in engineering effort, abstraction, technical debt and ease of throwing out code. We all trade one constraints for another, one set of assumptions with other.

**Comment by mikepham1011** [comment]
Hi @NutanNiraula, yeah I can see it from you comment that you want to see what I can do with the network layer. I have added a new RequestInterceptor class that helps handle auto-refresh token with retry mechanism, and the ability to handling error message with request from the API Managers directly. Thanks to that, I can remove redundant check for refreshing token in APIManagers classes since it is encapsulated in the RequestInterceptor. Feel free to take a look 😁!

It is available in dda176a
