### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by NutanNiraula** [mikepham1011/nimble-survey-app-ios#5]
You have indeed made some interesting choices for the UI but there are some issues with the current implementation. I would like to list them down. 

1. status bar color is not appropriate for the dark navigation bar
2. Take the survey button is not animating when user presses it
3. User cannot scroll the survey list and needs to tap the page control
4. Page control has cell selection state visible which shows square highlight over the cell, which breaks the illusion of page control and makes it look less native and poorly implemented
5. Maybe the loading indicator would be more visible with darker shade of blur effect, currently it is hard to read "Loading" text and spinner.

**Comment by mikepham1011** [comment]
Thank you so much for the detailed feedbacks! I would like to response to the list of items you mentioned as follow:

1. Really nice catch, I will adjust it.
2. Again nice catch, I will fix this issue.
3. This is intentional since looking at the design, my understand from it is that the indicator list is going to be dynamic and scrollable, and the main screen is actually a static full screen (not scrollable) for showing the current selected survey. As a result, I made the navigation indicator list as the main way to navigate through the survey list items. I guess I might have some misunderstanding here a bit since there is not much info about the UI and I just did it they way I think.
4. Great spot! I will fix this issue. This is because I am using a UITableView for the showing the dynamic indicators.
5. I think you are right, I will use a better loading indicator for showing the loading view nicely regardless of the background content.

**Comment by mikepham1011** [comment]
I just fixed all the issues you mentioned as follow:

1. Fixed in 7b8d299
2. Fixed in 6a2a2fd
3. Implemented in 696a3ae
4. Fixed in aed0a9d
5. Enhanced in bac0f2c

**Comment by NutanNiraula** [comment]
@mikepham1011 You have fixed most of the issues, I would like to add few nitpicks I have. For number 2, I believe using system button would have sufficed but I am ok with your implementation as well. It would be great to see the paging vertically as the page indicators are vertical but it's nice that users can use fluid gesture to engage with the app rather than crude interactions through taps only. Your loading indicator is great, one of the benefits of using vertical paging would be to add bottom loading spinner common these days that would avoid blocking user input and make user wait when the additional content is loading. But your fixes are all working, changing things would be very easy since you are using collectionView. 🎉  Scrollable page indicator is a really nice touch. 👍 

Here are some issues that I think we can still improve on:

1. I see a small UI issue which I would like to present. If the user slightly moves the page then the page indicator moves to other page and does not update back even when user is still at page one. 
![screenshot](https://i.imgur.com/hgMHSUK.gif)

2. I think we could add some dark overlay over the image in order to make text more legible. What do you think? In brighter images we would not be able to see the text as texts are in white.

3. This one is more of a nitpick, I just want to know your opinion on how you would solve it. Currently if the internet is down and user does not get any surveys, there is no way to add it unless user closes the app and reopens it. How would you solve the issue with the current implementation?

**Comment by mikepham1011** [comment]
@NutanNiraula, thanks again for your feedback on the app. In my opinion, I think that it is a bit odd from the design perspective that when we have a fullscreen-paging item display, then from that we opt to make it scroll vertically. Most of the time I see such a design, it should be scrollable horizontally and vertical scrolling should be more fit for an array of items that are visible in a screen region than one-page per screen design. Anyhow, you are definitely right on the fact that changing the scrolling directions will be easy based on my current implementation 😁

For your feedbacks list, I would like to answer as follow: 

1. Nice spot there, I will fix this issue.

2. I totally understand what you mean and agree with you on this. Actually, I have worked with very strict customers and this is something they would definitely pick out. How I usually resolve this is adding a light gray shadow layer below the text to help it looks more clear no matter what background they are placed on. Let me take care of this ^^.

3. I agree that if we use native components, it is a lot faster to implement a specific task that requires native behaviors. However, in certain cases like there are a lot of customized animations in the requirements that native navigation header doesn't have or when the provided designs are very simple and we don't need some extra features that the native navigation header has such as: blur navigation header background, present/dismiss view controllers horizontally, supporting arrays of UIBarButtonItems, etc. It is much more efficient to implement a custom navigation header. 
In my case, all the UI code for setting up the navigation header to make it look like design is placed in the storyboard file, and thus the code required for setting up the navigation view are reduced. All I need is to do to implement the refreshButton event for the navigation view. -> Less code best code.

4. No worries, I really like nitpicking, because it helps make the app even more perfect in terms of quality. The only question is do we have to time to do it 😄. To answer your question, as of now I see that we already has the refresh button in the navigation header. I have already implemented and tested the app in the case that we start the application without connection. As a result, in such cases what you can do is just to click the refresh button after having the connection back. It will trigger the load and show you the data without having to terminate the app.
However, we can leverage this manual behavior further by adding an observer for network change event. This way it will help user to load the data automatically without having to wait for the users to manually click on the refresh button. I don't see this requirement and thus I haven't implemented it yet, for now the refresh button on the top left corner is good enough.

**Comment by mikepham1011** [comment]
I just fixed some of the issues you mentioned on your latest comment as follow:

1. Fixed in 7b8d299
2. Enhanced in d2b5dc0

**Comment by mikepham1011** [comment]
I also make the scroll view of the surveys list scroll vertically to match with the vertical navigation indicators list. You can find the implementation in 5faf987. 😁

**Comment by NutanNiraula** [comment]
@mikepham1011 Sorry for the delay in response, we had holiday yesterday. You have nice responses and good implementations. 🎉  Before I end this session, I have some final questions 😁 

1. I saw that you have debug prints in your code. What do you think is the proper logging abstraction for a medium to large scale project?

2. What do you think about the automation in projects? Which tool do you think is better between Jenkins and Bitrise? 

3. Do you think CI and git workflows should be same for all the projects or do you believe that we should try to define process per project?

**Comment by mikepham1011** [comment]
Hi @NutanNiraula, no worries and thanks for letting me know! I didn't know about your holiday and thus I did feel worry a bit yesterday 😅. Regardless of that, I hope you guys enjoyed your holiday and come back strong today 😁. 

To answer your questions, I would like to list them out as follow:

1. Nice question there! To answer this question, I want to share my experience from my current large-scaled projects. What I would do is to create a separate Logger class instead of using directly prints function. Firstly, this logging layer will help us extract more information for a specific logging event such as: function name, function line, date of event and event log type (error, info, debug, verbose, warning, etc.). On top of that, we can easily control which environment (DEBUG, STAGING, PRODUCTION) that requires which logging events without having to clone the environment switching code everywhere you need to log. Finally, on last thing that I do specifically for PRODUCTION environment with my Logger class is to actually store an encrypted log file on the phone unlike DEBUG environment, where you can see logs directly in the console. By doing this, whenever there is an issue reported by our actual users, we can ask them to send the encrypted log file from their phones to our developer's email or to our server and from there, we can decrypt and extract an in-depth view of what happened under the hood before the issue occurred. This would help ease out our bug fixing process a lot.

2. Personally, I think automation in projects is a must-have thing, especially for medium to large projects. The idea is that we should automate things that we as developers do repeatedly (potentially everyday). This would help enhance productivity as automating workflows eliminate the need for manual work, which not only improves output, but it also frees up developers to apply their knowledge and advanced skills to other important tasks and projects. For an example, at the release date, normally we have to push all the latest code for the release branch, then create the release build, then wait for the build to finish, and after that we need to upload it to TestFlight, and finally wait for it to be available on TestFlight before users can receive and test the release build. This whole release process should take an hour to complete. Having a proper CI/CD setup will help us developers save that one hour every time we make a release, all we need to do is to commit the code to the release branch and continue to work on other tasks while the automated release process kicks in, and the benefit keeps adding up overtime. As a result, more work can be processed on a daily basis.

I have 2 years of experience working with Bitrise and I have heard of Jenkins already but I don't work with it yet. From my experience, I think Bitrise is a really great tool for setting up automated building flows, for both iOS and Android mobile development. Setting Bitrise up is very simple and it have great UI/UX flows on the platform as well. On the other hand, I am aware that Jenkins is quite complex to setup. The only downside from Bitrise that I can think of is that for a given account, if you want more building lanes for your app you have to pay and upgrade your account, while Jenkins is a free. As a result from my above experiences, I will opt to go with Bitrise as my prefer CI/CD tool. 😁

3. In my opinions, if we are talking about projects themselves, then I think CI and git workflows should be same for consistency purpose. With this way, when we have new team members from exist projects come to work in a new project, it will save us time training them about the flows again. The factors that diverse CI and git workflows should be the project's environment and the situation we are merging a PR. Let's say if we have a new feature that need to be available on DEV environment, our CI flow should just make sure all unit tests are passing. However, if we want to release that feature on STAGING environment, then our CI flow needs to create a release build to TestFlight besides validating unit tests, something like this.

**Comment by NutanNiraula** [comment]
Thanks for the reply. 🎉  This ends my review of the code, you have done well. You will be hearing from the team about the decision as soon as possible. It was true pleasure reviewing your code and getting to know you. I wish you all the very best. 🍀
